brew tap caskroom/cask
brew tap homebrew/versions
brew tap peco/peco
brew tap sanemat/font
brew update

brew install anyenv
brew install autojump
brew install automake
brew install brew-cask
brew install chromedriver
brew install cmake
brew install cmigemo
brew install ctags
brew install curl
brew install elasticsearch
brew install fzf
# for elasticsearch
brew install kibana
brew install gibo
brew install gist
brew install git
brew install ghq
brew install gnu-sed
brew install go
brew install heroku-toolbelt
brew install homebrew/php/composer
brew install hub
brew install imagemagick
brew install jpegoptim
brew install jq
brew install lolcat
brew install mozjpeg
brew install neovim
brew install nkf
#brew install nodebrew
brew install openssl
brew install optipng
brew install pcre
brew install peco
brew install pkg-config
brew install pngout
brew install postgresql
brew install pwgen
brew install pyenv
brew install rbenv
brew install readline
brew install reattach-to-user-namespace
brew install rename
brew install ricty
brew install ruby-build
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tree
brew install vim
brew install w3m
brew install wget
brew install xz
brew install yarn
brew install zopfli
brew install zsh
brew install zsh-completions
brew install tldr
