brew tap caskroom/cask
brew tap homebrew/versions
brew tap peco/peco
brew tap sanemat/font
brew update

brew install autojump
brew install brew-cask
brew install cmigemo
brew install chromedriver
brew install curl
brew install gibo
brew install gist
brew install git
brew install go
brew install gnu-sed
brew install heroku-toolbelt
brew install hub
brew install imagemagick
brew install jpegoptim
brew install jq
brew install mozjpeg
brew install neovim
brew install nkf
brew install nodebrew
brew install openssl
brew install optipng
brew install peco
brew install pngout
brew install postgresql
brew install homebrew/php/composer
brew install pwgen
brew install pyenv
brew install rbenv
brew install readline
brew install reattach-to-user-namespace
brew install ricty
brew install rename
brew install ruby-build
brew install tig
brew install tmux
brew install tree
brew install vim
brew install w3m
brew install wget
brew install yarn
brew install zopfli
brew install zsh
brew install zsh-completions
