[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    let b:dwm_disabled = 1
    let b:auto_cursorline_disabled = 1
    nnoremap <silent><buffer> <C-n> j
    nnoremap <silent><buffer> <C-p> k
    nnoremap <silent><buffer><expr> <BS>    denite#do_map('move_up_path')
    nnoremap <silent><buffer><expr> <C-a>   denite#do_map('do_action', 'my_file_rec')
    nnoremap <silent><buffer><expr> <C-c>   denite#do_map('quit')
    nnoremap <silent><buffer><expr> <C-g>   denite#do_map('do_action', 'grep')
    nnoremap <silent><buffer><expr> <C-n>   denite#do_map('do_action', 'dwm_new')
    nnoremap <silent><buffer><expr> <C-x>   denite#do_map('do_action', 'quick_move')
    nnoremap <silent><buffer><expr> <CR>    denite#do_map('do_action')
    nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select).'j'
    nnoremap <silent><buffer><expr> <Tab>   denite#do_map('choose_action')
    nnoremap <silent><buffer><expr> a       denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> p       denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q       denite#do_map('quit')
  endfunction

  call denite#custom#alias('source', 'file/rec/git', 'file/rec')
  call denite#custom#var('file/rec/git', 'command',
      \ ['git', 'ls-files', '-co', '--exclude-standard'])

  nmap <silent> ,uf :<C-u>Denite file/rec<CR>
  nmap <silent> ,uh :<C-u>Denite file/rec/git<CR>
  nmap <silent> ,ug :<C-u>Denite grep<CR>
  nmap <silent> ,ub :<C-u>Denite buffer<CR>
  nmap <silent> ,uy :<C-u>Denite neoyank<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
colorscheme monokain
'''

[[plugins]]
repo = 'haya14busa/vim-migemo'
hook_add = '''
  if executable('cmigemo')
    cnoremap <expr><C-N> migemosearch#replace_search_word()."\<CR>"
  endif
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'oieioi/increment-day.vim'
hook_add = '''
  nnoremap <C-a> :IncrementDay<CR>
  nnoremap <C-x> :DecrementDay<CR>
'''

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'pedrohdz/vim-yaml-folds'

[[plugins]]
repo = 'rhysd/ghpr-blame.vim'

[[plugins]]
repo = 'rhysd/migemo-search.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_add = 'nnoremap <C-_> :MundoToggle<CR>'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'csscomb/vim-csscomb'

