[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  let g:denite_enable_start_insert=1

  " git ls-files するための設定
  call denite#custom#source(
        \ 'file/rec', 'matchers', ['matcher_ignore_globs'])
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
        \ [
        \ 'tmp/',
        \ '.git/',
        \ 'images/',
        \ 'img/',
        \ 'node_modules/'])
  call denite#custom#alias('source', 'file/rec/git', 'file/rec')
  call denite#custom#var('file/rec/git', 'command',
        \ ['git', 'ls-files', '-co', '--exclude-standard'])
  call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>')
  call denite#custom#map('insert', "<C-p>", '<denite:move_to_previous_line>')

  " grep -> ag
  call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  " key bind
  nnoremap <silent> ,uy :<C-u>Denite neoyank<CR>
  nnoremap <silent> ,ub :<C-u>Denite buffer<CR>
  nnoremap <silent> ,ug :<C-u>Denite grep<CR>
  nnoremap <silent> ,uf :<C-u>DeniteBufferDir -buffer-name=files file<CR>
  nnoremap <silent> ,uu :<C-u>Denite file_mru buffer<CR>
  nnoremap <silent> ,uh :<C-u>Denite `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
colorscheme monokain
'''

[[plugins]]
repo = 'haya14busa/vim-migemo'
hook_add = '''
  if executable('cmigemo')
    cnoremap <expr><C-N> migemosearch#replace_search_word()."\<CR>"
  endif
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'oieioi/increment-day.vim'
hook_add = '''
  nnoremap <C-a> :IncrementDay<CR>
  nnoremap <C-x> :DecrementDay<CR>
'''

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'pedrohdz/vim-yaml-folds'

[[plugins]]
repo = 'rhysd/ghpr-blame.vim'

[[plugins]]
repo = 'rhysd/migemo-search.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_add = 'nnoremap <C-_> :MundoToggle<CR>'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'csscomb/vim-csscomb'
